### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sbellem** [sbellem/sgx-bsm#1]
- [ ] update readme
- [ ] add some docs
- [ ] simulate verification with smart contract
- [ ] consume inputs from file
- [ ] sign hash of inputs, and add this as part of what must be verified by smart contract -- this is to make sure that the correct inputs were used
